services:
  - type: web
    name: cv-analysis-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://cv-analysis-backend.onrender.com 