services:
  - type: web
    name: cv-analysis-backend
    env: dotnet
    plan: free
    buildCommand: dotnet restore && dotnet publish -c Release -o out
    startCommand: dotnet out/CvAnalysis.Server.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
      
      # Veritabanı bağlantısı
      - key: ConnectionStrings__DefaultConnection
        fromSecret: false # Değeri Render arayüzünden alacak

      # Azure Document Intelligence (eski adıyla Form Recognizer)
      - key: AzureAi__DocumentIntelligenceEndpoint
        fromSecret: false # Değeri Render arayüzünden alacak
      - key: AzureAi__DocumentIntelligenceKey
        fromSecret: true # Değeri Render arayüzünden alacak (gizli)

      # Azure OpenAI
      - key: AzureAi__OpenAiEndpoint
        fromSecret: false # Değeri Render arayüzünden alacak
      - key: AzureAi__OpenAikey # 'k' harfinin küçük olduğuna dikkat!
        fromSecret: true # Değeri Render arayüzünden alacak (gizli)
      - key: AzureAi__OpenAiDeployment
        fromSecret: false # Değeri Render arayüzünden alacak